action_tiles: "214x106>"
expert_tiles: "133x133>"
location_bonuses: "90x90>"
company_goals: "778x554>"
upgrade_tokens: "129x129>"
cruises: "311x113>"
guest_bonuses: "283x183>"
technologies: "243x102>"
gear_meeples: "58x58>"
guest_meeples: "36.01x75.78>"
cruise_mocks: "580.96x293.29>"